### ISSUE TITLE
Contao 4 Compatibility

### ISSUE THREAD

**Issue by omuellersch** [derhaeuptling/referer-spam-blocker#1]
THamks for this nice Contao Extension! Will it be available for Contao 4.4+ in the Contao Manager?

**Comment by Metis77** [comment]
this plugin relays on .htaccess file.

As Contao 4x supports nginx,  Apache and therefor .htaccess files would be ignored.

Therefor updating this plugin would make no sense.

But:
Google Analytics now has special referer spam filters, you could enable instead.
